### ISSUE TITLE
Website Peer Review

### ISSUE THREAD

**Issue by smcdermott3** [Jiaxinliu-cindy/Project-1#2]
Please add the URL to your website so we may review it.

**Comment by Jiaxinliu-cindy** [comment]
http://www.sugarforever.live/

**Comment by Jiaxinliu-cindy** [comment]
Sorry, just saw this. The link has been added.

**Comment by smcdermott3** [comment]
Thanks for adding it!

Bugs:
1) Reduce the size of the Homepage photo to allow for faster loading
2) On the "About Coyote" page, try linking the Wikipedia link to a relevant word.
Honestly I couldn't really find any bugs. This is a very well-built website.

Content:
1) On the contact page, make the feedback box larger so typing is easier for the user.
2) Individualize the alt's and titles on the photo gallery.

This is a really sweet website and great memorial page for Sugar.

**Comment by Jiaxinliu-cindy** [comment]
Thank you for the detailed feedback, I have updated the pages.
