### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by avenigalla32** [Jiaxinliu-cindy/Project-1#3]
Bugs:
1. images don't have alt=""
2. the "To Sugar" page is blank

Suggestions:
1. You could try to lock the nav bar so that you can see it even when you scroll down
2. I would consider adding pictures to the "Sugar's Story" page cause it's really text heavy

**Comment by Jiaxinliu-cindy** [comment]
Thank you for your feedback! I have updated the pages.
