### ISSUE TITLE
Peer Review by Cristina Toledo

### ISSUE THREAD

**Issue by ctoledo1** [Jiaxinliu-cindy/Project-1#4]
Cindy great job on your page. The gallery is impressive! 

Bugs:
1. I would make your form on "contact us" more detailed. I also would suggest to add a contact us page. 

Content: 
1. I would add pictures of coyotes or some infographics on the "About Coyote's Page"
2. I would add a bit more on the homepage as of text where the objective of the page is more clear. 
3. I would also format the tips for dealing with coyotes with bullets so it is more clear.

**Comment by Jiaxinliu-cindy** [comment]
Thank you for the feedback, i have updated my contact page.
